### PR TITLE
Fix cgrates not recognizing negative UTC offsets in valid RFC3339 datetime format

### PR DESCRIPTION
**Pull request by powerpbx**
https://github.com/irontec/ivozprovider/issues/801

### CODE REVIEW

**Comment by powerpbx** [comment]
Won't work.  Closing until we work out how to isolate the timezone offset at the end.

**Comment by powerpbx** [comment]
It appears that Cgrates does not check for one of the types of valid RFC3339 timedate formats. 

To reproduce, assuming `b1` is an existing tpid row in ivozprovider.tp_rating_profiles table
```
timedatectl set-timezone America/Los_Angeles
systemctl restart cgrates

# cgr-console
cgr> load_tp_from_stordb TPid="b1" FlushDb=false DryRun=true Validate=false Cleanup=false
Error executing command: SERVER_ERROR: cannot parse activation time from 2018-11-24T08:00:00-08:00
exit

timedatectl set-timezone America/New_York
systemctl restart cgrates

# cgr-console
cgr> load_tp_from_stordb TPid="b1" FlushDb=false DryRun=true Validate=false Cleanup=false
Error executing command: SERVER_ERROR: cannot parse activation time from 2018-11-24T08:00:00-05:00
exit

timedatectl set-timezone UTC
systemctl restart cgrates

# cgr-console
cgr> load_tp_from_stordb TPid="b1" FlushDb=false DryRun=true Validate=false Cleanup=false
"OK"
exit

timedatectl set-timezone Europe/Berlin
systemctl restart cgrates

# cgr-console
cgr> load_tp_from_stordb TPid="b1" FlushDb=false DryRun=true Validate=false Cleanup=false
"OK"
```
It looks like the problem may be here
https://github.com/irontec/cgrates/blob/76bb3e0a20744913524de6d2286e2a25c6313fb6/utils/coreutils.go#L242

which does not appear to check for negative timezone offsets that are in valid RFC3339 format.

Here is some sample code that checks for negative timezone offsets. 
 https://play.golang.org/p/HiikqFKdYBZ
```
package main

import (
    "fmt"
    "time"
    "math"
)

func main() {
    date := "2018-12-03T22:23:22-01:00"
    t, err := time.Parse(time.RFC3339, date)
    _, tzOffset:= t.Zone()
    i := float64(tzOffset)
    fmt.Println(tzOffset)
    fmt.Println("Is it negative: ", math.Signbit(i)) 
    if err != nil {
		fmt.Println("error", err)
		return
	}
}
```
We also opened an issue on the cgrates github site.

https://github.com/cgrates/cgrates/issues/1331

**Comment by Kaian** [comment]
Is https://github.com/cgrates/cgrates/pull/1333/commits/107f6e629914106e1ddfd547c3c6f04e356127cb the  fix for reported problem?

We add that patch and have some tests.

**Comment by cruzccl** [comment]
Fixed with 72fa43d91251d413591665f20ed1b3239a9f59bf and irontec/ivozprovider#833

Thanks for your work, it is highly appreciated :+1: 

Regards,

**Pull request closed without merging**
